-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 19:59:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elden
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elden` DEFAULT CHARACTER SET utf8 ;
USE `elden` ;

-- -----------------------------------------------------
-- Table `elden`.`dragoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elden`.`dragoes` (
  `id_dragao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `localizacao` VARCHAR(50) NOT NULL,
  `elemento` VARCHAR(50) NOT NULL,
  `forca` INT NOT NULL,
  `descricao` TEXT,
  PRIMARY KEY (`id_dragao`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `elden`.`cavaleiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elden`.`cavaleiros` (
  `id_cavaleiro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `classe` VARCHAR(50) NOT NULL,
  `nivel` INT NOT NULL,
  `dragao_id` INT,
  PRIMARY KEY (`id_cavaleiro`),
  INDEX `fk_cavaleiros_dragoes_idx` (`dragao_id` ASC),
  CONSTRAINT `fk_cavaleiros_dragoes`
    FOREIGN KEY (`dragao_id`)
    REFERENCES `dragoes`(`id_dragao`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
